# df = pd.read_csv()

In [1]:
import pandas as pd
ukraine = pd.read_csv('http://bit.ly/ukraine_sanctions_csv')

In [2]:
ukraine

,,,,,,,,,,,,,,,,,,,,,,,,,,,Last Updated,30/08/2019
Name 6,Name 1,Name 2,Name 3,Name 4,Name 5,Title,DOB,Town of Birth,Country of Birth,Nationality,Passport Details,NI Number,Position,Address 1,Address 2,Address 3,Address 4,Address 5,Address 6,Post/Zip Code,Country,Other Information,Group Type,Alias Type,Regime,Listed On,Last Updated,Group ID
GAZPROM NEFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2014. Not subject to an asset freeze.,Entity,Prime Alias,Ukraine (Sovereignty),12/09/2014,12/09/2014,13119
GAZPROMBANK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2014. Not subject to an asset freeze.,Entity,Prime Alias,Ukraine (Sovereignty),01/08/2014,01/08/2014,13081
OPK OBORONPROM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2014. Not subject to an asset freeze.,Entity,Prime Alias,Ukraine (Sovereignty),12/09/2014,12/09/2014,13120
ROSNEFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2014. Not subject to an asset freeze.,Entity,Prime Alias,Ukraine (Sovereignty),12/09/2014,12/09/2014,13117
ROSSELKHOZBANK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2014. Not subject to an asset freeze.,Entity,Prime Alias,Ukraine (Sovereignty),01/08/2014,01/08/2014,13083
SBERBANK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2014. Not subject to an asset freeze.,Entity,Prime Alias,Ukraine (Sovereignty),01/08/2014,01/08/2014,13079
TRANSNEFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2014. Not subject to an asset freeze.,Entity,Prime Alias,Ukraine (Sovereignty),12/09/2014,12/09/2014,13118
UNITED AIRCRAFT CORPORATION,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2014. Not subject to an asset freeze.,Entity,Prime Alias,Ukraine (Sovereignty),12/09/2014,12/09/2014,13121
URALVAGONZAVOD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2014. Not subject to an asset freeze.,Entity,Prime Alias,Ukraine (Sovereignty),12/09/2014,12/09/2014,13122
VNESHECONOMBANK (VEB),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2014. Not subject to an asset freeze.,Entity,Prime Alias,Ukraine (Sovereignty),01/08/2014,01/08/2014,13082
VTB BANK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2014. Not subject to an asset freeze.,Entity,Prime Alias,Ukraine (Sovereignty),01/08/2014,01/08/2014,13080

In [3]:
ukraine = pd.read_csv('../Datasets/ukraine_inv_bans.csv')

In [4]:
ukraine

,Last Updated,30/08/2019,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28
0,Name 6,Name 1,Name 2,Name 3,Name 4,Name 5,Title,DOB,Town of Birth,Country of Birth,...,Address 6,Post/Zip Code,Country,Other Information,Group Type,Alias Type,Regime,Listed On,Last Updated,Group ID
1,GAZPROM NEFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),12/09/2014,12/09/2014,13119
2,GAZPROMBANK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),01/08/2014,01/08/2014,13081
3,OPK OBORONPROM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),12/09/2014,12/09/2014,13120
4,ROSNEFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),12/09/2014,12/09/2014,13117
5,ROSSELKHOZBANK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),01/08/2014,01/08/2014,13083
6,SBERBANK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),01/08/2014,01/08/2014,13079
7,TRANSNEFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),12/09/2014,12/09/2014,13118
8,UNITED AIRCRAFT CORPORATION,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),12/09/2014,12/09/2014,13121
9,URALVAGONZAVOD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),12/09/2014,12/09/2014,13122
10,VNESHECONOMBANK (VEB),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),01/08/2014,01/08/2014,13082
11,VTB BANK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),01/08/2014,01/08/2014,13080

In [5]:
import os
filepath = os.path.join('..', 'Datasets', 'ukraine_inv_bans.csv')
ukraine = pd.read_csv(filepath)

In [6]:
ukraine

,Last Updated,30/08/2019,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28
0,Name 6,Name 1,Name 2,Name 3,Name 4,Name 5,Title,DOB,Town of Birth,Country of Birth,...,Address 6,Post/Zip Code,Country,Other Information,Group Type,Alias Type,Regime,Listed On,Last Updated,Group ID
1,GAZPROM NEFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),12/09/2014,12/09/2014,13119
2,GAZPROMBANK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),01/08/2014,01/08/2014,13081
3,OPK OBORONPROM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),12/09/2014,12/09/2014,13120
4,ROSNEFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),12/09/2014,12/09/2014,13117
5,ROSSELKHOZBANK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),01/08/2014,01/08/2014,13083
6,SBERBANK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),01/08/2014,01/08/2014,13079
7,TRANSNEFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),12/09/2014,12/09/2014,13118
8,UNITED AIRCRAFT CORPORATION,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),12/09/2014,12/09/2014,13121
9,URALVAGONZAVOD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),12/09/2014,12/09/2014,13122
10,VNESHECONOMBANK (VEB),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),01/08/2014,01/08/2014,13082
11,VTB BANK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),01/08/2014,01/08/2014,13080

In [7]:
eu = pd.read_csv('http://bit.ly/eu_sanctions_csv', sep = ';')

c:\users\devante\appdata\local\programs\python\python37\lib\site-packages\IPython\core\interactiveshell.py:3051: DtypeWarning: Columns (3,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [8]:
eu

,fileGenerationDate,Entity_LogicalId,Entity_EU_ReferenceNumber,Entity_UnitedNationId,Entity_DesignationDate,Entity_DesignationDetails,Entity_Remark,Entity_SubjectType,Entity_SubjectType_ClassificationCode,Entity_Regulation_Type,...,Citizenship_LogicalId,Citizenship_RegulationLanguage,Citizenship_Remark,Citizenship_Regulation_Type,Citizenship_Regulation_OrganisationType,Citizenship_Regulation_PublicationDate,Citizenship_Regulation_EntryIntoForceDate,Citizenship_Regulation_NumberTitle,Citizenship_Regulation_Programme,Citizenship_Regulation_PublicationUrl
0,22/01/2020,1,EU.36.64,NaN,NaN,NaN,NaN,P,person,amendment,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,22/01/2020,1,EU.36.64,NaN,NaN,NaN,NaN,P,person,amendment,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,22/01/2020,1,EU.36.64,NaN,NaN,NaN,NaN,P,person,amendment,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,22/01/2020,13,EU.27.28,NaN,NaN,NaN,(UNSC RESOLUTION 1483),P,person,regulation,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,22/01/2020,13,EU.27.28,NaN,NaN,NaN,(UNSC RESOLUTION 1483),P,person,regulation,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12167,22/01/2020,121500,EU.5265.47,MLi.008,2019-07-10,NaN,(UN ID: MLi.008)\n(Date of UN designation: 201...,P,person,amendment,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12168,22/01/2020,121500,EU.5265.47,MLi.008,2019-07-10,NaN,(UN ID: MLi.008)\n(Date of UN designation: 201...,P,person,amendment,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12169,22/01/2020,121500,EU.5265.47,MLi.008,2019-07-10,NaN,(UN ID: MLi.008)\n(Date of UN designation: 201...,P,person,amendment,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12170,22/01/2020,121500,EU.5265.47,MLi.008,2019-07-10,NaN,(UN ID: MLi.008)\n(Date of UN designation: 201...,P,person,amendment,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12171,22/01/2020,121500,EU.5265.47,MLi.008,2019-07-10,NaN,(UN ID: MLi.008)\n(Date of UN designation: 201...,P,person,amendment,...,121571.0,EN,NaN,amendment,council,2020-01-08,2020-01-08,2020/8 (OJ L 4I),MLI,https://eur-lex.europa.eu/legal-content/EN/TXT...

In [9]:
ofac = pd.read_csv('http://bit.ly/ofac_sanctions_csv', header=None, names=['ent_num','SDN_Name','SDN_Type','Program','Title','Call_Sign','Vess_type','Tonnage','GRT','Vess_flag','Vess_owner','Remarks'])

In [10]:
ofac

,ent_num,SDN_Name,SDN_Type,Program,Title,Call_Sign,Vess_type,Tonnage,GRT,Vess_flag,Vess_owner,Remarks
0,9639,"HANIYA, Ismail Abdul Salah",individual,NS-PLC,-0-,-0-,-0-,-0-,-0-,-0-,-0-,DOB 1962; POB Shati.
1,9640,"ABU TEIR, Mohammed",individual,NS-PLC,-0-,-0-,-0-,-0-,-0-,-0-,-0-,DOB 1951; POB Umm Tuba.
2,9641,"AL-SHANTI, Jamileh Abdullah",individual,NS-PLC,-0-,-0-,-0-,-0-,-0-,-0-,-0-,DOB 1955; POB Jabalia Camp.
3,9642,"NU'MAN ALAEDDIN, Mohammed Jamal",individual,NS-PLC,-0-,-0-,-0-,-0-,-0-,-0-,-0-,DOB 1959.
4,9643,"MANSOUR, Yasser Daoud",individual,NS-PLC,-0-,-0-,-0-,-0-,-0-,-0-,-0-,"DOB 1967; POB Nablus, West Bank."
...,...,...,...,...,...,...,...,...,...,...,...,...
371,23571,STRAKHOVOVE OBSHCHESTVO SURGUTNEFTEGAZ OOO,-0-,UKRAINE-EO13662,-0-,-0-,-0-,-0-,-0-,-0-,-0-,Website www.sngi.ru; Executive Order 13662 Dir...
372,23572,KIRISHIAVTOSERVIS OOO,-0-,UKRAINE-EO13662,-0-,-0-,-0-,-0-,-0-,-0-,-0-,Website www.kirishiavtoservis.ru; Executive Or...
373,23577,SNGB AO,-0-,UKRAINE-EO13662,-0-,-0-,-0-,-0-,-0-,-0-,-0-,Website www.sngb.ru; Executive Order 13662 Dir...
374,26182,"KAYAKIRAN, Evren",individual,FSE-IR,-0-,-0-,-0-,-0-,-0-,-0-,-0-,DOB 08 Feb 1980; citizen Turkey; Gender Male; ...
375,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
ofac = pd.read_csv('http://bit.ly/ofac_sanctions_csv', index_col='SDN_Name', header=None, names=['ent_num','SDN_Name','SDN_Type','Program','Title','Call_Sign','Vess_type','Tonnage','GRT','Vess_flag','Vess_owner','Remarks'])

In [12]:
ofac

,ent_num,SDN_Type,Program,Title,Call_Sign,Vess_type,Tonnage,GRT,Vess_flag,Vess_owner,Remarks
SDN_Name,,,,,,,,,,,
"HANIYA, Ismail Abdul Salah",9639,individual,NS-PLC,-0-,-0-,-0-,-0-,-0-,-0-,-0-,DOB 1962; POB Shati.
"ABU TEIR, Mohammed",9640,individual,NS-PLC,-0-,-0-,-0-,-0-,-0-,-0-,-0-,DOB 1951; POB Umm Tuba.
"AL-SHANTI, Jamileh Abdullah",9641,individual,NS-PLC,-0-,-0-,-0-,-0-,-0-,-0-,-0-,DOB 1955; POB Jabalia Camp.
"NU'MAN ALAEDDIN, Mohammed Jamal",9642,individual,NS-PLC,-0-,-0-,-0-,-0-,-0-,-0-,-0-,DOB 1959.
"MANSOUR, Yasser Daoud",9643,individual,NS-PLC,-0-,-0-,-0-,-0-,-0-,-0-,-0-,"DOB 1967; POB Nablus, West Bank."
...,...,...,...,...,...,...,...,...,...,...,...
STRAKHOVOVE OBSHCHESTVO SURGUTNEFTEGAZ OOO,23571,-0-,UKRAINE-EO13662,-0-,-0-,-0-,-0-,-0-,-0-,-0-,Website www.sngi.ru; Executive Order 13662 Dir...
KIRISHIAVTOSERVIS OOO,23572,-0-,UKRAINE-EO13662,-0-,-0-,-0-,-0-,-0-,-0-,-0-,Website www.kirishiavtoservis.ru; Executive Or...
SNGB AO,23577,-0-,UKRAINE-EO13662,-0-,-0-,-0-,-0-,-0-,-0-,-0-,Website www.sngb.ru; Executive Order 13662 Dir...
"KAYAKIRAN, Evren",26182,individual,FSE-IR,-0-,-0-,-0-,-0-,-0-,-0-,-0-,DOB 08 Feb 1980; citizen Turkey; Gender Male; ...
NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
ofac = pd.read_csv('http://bit.ly/ofac_sanctions_csv', usecols=['SDN_Name','SDN_Type','Program'], header=None, names=['ent_num','SDN_Name','SDN_Type','Program','Title','Call_Sign','Vess_type','Tonnage','GRT','Vess_flag','Vess_owner','Remarks'])

In [14]:
ofac

                                       SDN_Name    SDN_Type          Program
0                    HANIYA, Ismail Abdul Salah  individual           NS-PLC
1                            ABU TEIR, Mohammed  individual           NS-PLC
2                   AL-SHANTI, Jamileh Abdullah  individual           NS-PLC
3               NU'MAN ALAEDDIN, Mohammed Jamal  individual           NS-PLC
4                         MANSOUR, Yasser Daoud  individual           NS-PLC
..                                          ...         ...              ...
371  STRAKHOVOVE OBSHCHESTVO SURGUTNEFTEGAZ OOO        -0-   UKRAINE-EO13662
372                       KIRISHIAVTOSERVIS OOO        -0-   UKRAINE-EO13662
373                                     SNGB AO        -0-   UKRAINE-EO13662
374                            KAYAKIRAN, Evren  individual           FSE-IR
375                                         NaN         NaN              NaN

[376 rows x 3 columns]

In [15]:
ofac = pd.read_csv('http://bit.ly/ofac_sanctions_csv', usecols=['SDN_Name'], squeeze=True, header=None, names=['ent_num','SDN_Name','SDN_Type','Program','Title','Call_Sign','Vess_type','Tonnage','GRT','Vess_flag','Vess_owner','Remarks'])

In [16]:
ofac

0                      HANIYA, Ismail Abdul Salah
1                              ABU TEIR, Mohammed
2                     AL-SHANTI, Jamileh Abdullah
3                 NU'MAN ALAEDDIN, Mohammed Jamal
4                           MANSOUR, Yasser Daoud
                          ...
371    STRAKHOVOVE OBSHCHESTVO SURGUTNEFTEGAZ OOO
372                         KIRISHIAVTOSERVIS OOO
373                                       SNGB AO
374                              KAYAKIRAN, Evren
375                                           NaN
Name: SDN_Name, Length: 376, dtype: object

In [17]:
type(ofac)

pandas.core.series.Series

In [18]:
isinstance(ofac, pd.Series)

True

In [19]:
ofac = pd.read_csv('http://bit.ly/ofac_sanctions_csv', prefix='Col_', header=None)

In [20]:
ofac

,Col_0,Col_1,Col_2,Col_3,Col_4,Col_5,Col_6,Col_7,Col_8,Col_9,Col_10,Col_11
0,9639,"HANIYA, Ismail Abdul Salah",individual,NS-PLC,-0-,-0-,-0-,-0-,-0-,-0-,-0-,DOB 1962; POB Shati.
1,9640,"ABU TEIR, Mohammed",individual,NS-PLC,-0-,-0-,-0-,-0-,-0-,-0-,-0-,DOB 1951; POB Umm Tuba.
2,9641,"AL-SHANTI, Jamileh Abdullah",individual,NS-PLC,-0-,-0-,-0-,-0-,-0-,-0-,-0-,DOB 1955; POB Jabalia Camp.
3,9642,"NU'MAN ALAEDDIN, Mohammed Jamal",individual,NS-PLC,-0-,-0-,-0-,-0-,-0-,-0-,-0-,DOB 1959.
4,9643,"MANSOUR, Yasser Daoud",individual,NS-PLC,-0-,-0-,-0-,-0-,-0-,-0-,-0-,"DOB 1967; POB Nablus, West Bank."
...,...,...,...,...,...,...,...,...,...,...,...,...
371,23571,STRAKHOVOVE OBSHCHESTVO SURGUTNEFTEGAZ OOO,-0-,UKRAINE-EO13662,-0-,-0-,-0-,-0-,-0-,-0-,-0-,Website www.sngi.ru; Executive Order 13662 Dir...
372,23572,KIRISHIAVTOSERVIS OOO,-0-,UKRAINE-EO13662,-0-,-0-,-0-,-0-,-0-,-0-,-0-,Website www.kirishiavtoservis.ru; Executive Or...
373,23577,SNGB AO,-0-,UKRAINE-EO13662,-0-,-0-,-0-,-0-,-0-,-0-,-0-,Website www.sngb.ru; Executive Order 13662 Dir...
374,26182,"KAYAKIRAN, Evren",individual,FSE-IR,-0-,-0-,-0-,-0-,-0-,-0-,-0-,DOB 08 Feb 1980; citizen Turkey; Gender Male; ...
375,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
ukraine = pd.read_csv('../Datasets/ukraine_inv_bans.csv', mangle_dupe_cols=True, header=1)

In [24]:
ukraine

,Name 6,Name 1,Name 2,Name 3,Name 4,Name 5,Title,DOB,Town of Birth,Country of Birth,...,Address 6,Post/Zip Code,Country,Other Information,Group Type,Alias Type,Regime,Listed On,Last Updated,Group ID
0,GAZPROM NEFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),12/09/2014,12/09/2014,13119
1,GAZPROMBANK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),01/08/2014,01/08/2014,13081
2,OPK OBORONPROM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),12/09/2014,12/09/2014,13120
3,ROSNEFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),12/09/2014,12/09/2014,13117
4,ROSSELKHOZBANK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),01/08/2014,01/08/2014,13083
5,SBERBANK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),01/08/2014,01/08/2014,13079
6,TRANSNEFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),12/09/2014,12/09/2014,13118
7,UNITED AIRCRAFT CORPORATION,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),12/09/2014,12/09/2014,13121
8,URALVAGONZAVOD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),12/09/2014,12/09/2014,13122
9,VNESHECONOMBANK (VEB),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),01/08/2014,01/08/2014,13082
10,VTB BANK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Listed under Council Regulation (EU) No. 833/2...,Entity,Prime Alias,Ukraine (Sovereignty),01/08/2014,01/08/2014,13080

In [27]:
ukraine.dtypes

Name 6                object
Name 1               float64
Name 2               float64
Name 3               float64
Name 4               float64
Name 5               float64
Title                float64
DOB                  float64
Town of Birth        float64
Country of Birth     float64
Nationality          float64
Passport Details     float64
NI Number            float64
Position             float64
Address 1            float64
Address 1.1          float64
Address 3            float64
Address 4            float64
Address 5            float64
Address 6            float64
Post/Zip Code        float64
Country              float64
Other Information     object
Group Type            object
Alias Type            object
Regime                object
Listed On             object
Last Updated          object
Group ID               int32
dtype: object

In [26]:
ukraine = pd.read_csv('../Datasets/ukraine_inv_bans.csv', dtype={'Group ID': int}, header=1)

In [30]:
uk = pd.read_csv('http://bit.ly/ukhmt_sanctions_csv', engine='python')

In [31]:
uk

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Last Updated  \
Name 6          Name 1    Name 2        Name 3 Name 4 Name 5 Title DOB        Town of Birth                                 Country of Birth Nationality              Passport Details                                   NI Number Position                                           Address 1 Address 2 Address 3 Address 4 Address 5 Address 6 Post/Zip Code Country                  Other Information                                  Group Type Alias Type  Regime                                             Listed On   Last Updated
AL-QAHTANI      Sheikh    Farooq        NaN    NaN    NaN    NaN   00/00/1980 NaN                                           Saudi Arabia     1) Saudi Arabia 2) Qatar Passport No: 592667 (Qatari passport issued on ... NaN       NaN                                                NaN       NaN       NaN       NaN       NaN       NaN       NaN           Afghanistan (since 2009) UN Ref QDe.004. Emir for the eastern zone of Af... Individual AKA         The ISIL (Da'esh) and Al-Qaida organisations       01/04/2016    01/04/2016
                                                                   00/00/1981 NaN                                           Saudi Arabia     1) Saudi Arabia 2) Qatar Passport No: 592667 (Qatari passport issued on ... NaN       NaN                                                NaN       NaN       NaN       NaN       NaN       NaN       NaN           Afghanistan (since 2009) UN Ref QDe.004. Emir for the eastern zone of Af... Individual AKA         The ISIL (Da'esh) and Al-Qaida organisations       01/04/2016    01/04/2016
ANSAR AL SHARIA NaN       NaN           NaN    NaN    NaN    NaN   NaN        NaN                                           NaN              NaN                      NaN                                                NaN       NaN                                                NaN       NaN       NaN       NaN       NaN       NaN       NaN           NaN                      UN REF:QE.A.146.14. Also referred to as Ansar a... Entity     AKA         The ISIL (Da'esh) and Al-Qaida organisations       29/11/2014    02/12/2014
IL              Kim Kyong NaN           NaN    NaN    NaN    NaN   01/08/1979 NaN                                           NaN              NaN                      Passport No. 836210029                             NaN       Foreign Trade Bank deputy chief representative ... Libya     NaN       NaN       NaN       NaN       NaN       NaN           NaN                      Annex XIII. UN Listing. UN Ref.KPI.067.            Individual Prime Alias North Korea (Democratic People's Republic of Ko... 22/12/2017    09/01/2018
...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ...
ZULKARNAIN      NaN       NaN           NaN    NaN    NaN    NaN   00/00/1963 Gebang village, Masaran, Sragen, Central Java Indonesia        Indonesian               NaN                                                NaN       NaN                                                NaN       NaN       NaN       NaN       NaN       NaN       NaN           NaN                      UN Ref QI.Z.187.05. Also referred to as Murshid.   Individual AKA         The ISIL (Da'esh) and Al-Qaida organisations       18/05/2005    29/04/2019
ZULKARNAN       NaN       NaN           NaN    NaN    NaN    NaN   00/00/1963 Gebang village, Masaran, Sragen, Central Java Indonesia        Indonesian               NaN                                                NaN       NaN                                                NaN       NaN       NaN       NaN       NaN       NaN       NaN           NaN                      UN Ref QI.Z.187.05. Also referred to as Murshid.   Individual AKA         The ISIL (Da'esh) and Al-Qaida organisations       18/05/2005    29/04/2019
ZULKARNIN       NaN       NaN           NaN    NaN    NaN    NaN   00/00/1963 Gebang village, Masaran, Sragen, Central Java Indonesia        Indonesian               NaN                                                NaN       NaN                                                NaN       NaN       NaN       NaN       NaN       NaN       NaN           NaN                      UN Ref QI.Z.187.05. Also referred to as Murshid.   Individual AKA         The ISIL (Da'esh) and Al-Qaida organisations       18/05/2005    29/04/2019
ZYMA            Petro     Anatoliyovych NaN    NaN    NaN    NaN   18/01/1970 Artemivsk, Donetsk Oblast                     Ukraine          NaN                      NaN                                                NaN       Head of the Crimean Security Service (SBU) (Sin... NaN       NaN       NaN       NaN       NaN       NaN       NaN           NaN                      NaN                                                Individual AKA         Ukraine (Sovereignty)                              18/03/2014    15/03/2018
                                                                   29/03/1965 Artemivsk, Donetsk Oblast                     Ukraine          NaN                      NaN                                                NaN       Head of the Crimean Security Service (SBU) (Sin... NaN       NaN       NaN       NaN       NaN       NaN       NaN           NaN                      NaN                                                Individual AKA         Ukraine (Sovereignty)                              18/03/2014    15/03/2018

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 26/11/2019
Name 6          Name 1    Name 2        Name 3 Name 4 Name 5 Title DOB        Town of Birth                                 Country of Birth Nationality              Passport Details                                   NI Number Position                                           Address 1 Address 2 Address 3 Address 4 Address 5 Address 6 Post/Zip Code Country                  Other Information                                  Group Type Alias Type  Regime                                             Listed On    Group ID
AL-QAHTANI      Sheikh    Farooq        NaN    NaN    NaN    NaN   00/00/1980 NaN                                           Saudi Arabia     1) Saudi Arabia 2) Qatar Passport No: 592667 (Qatari passport issued on ... NaN       NaN                                                NaN       NaN       NaN       NaN       NaN       NaN       NaN           Afghanistan (since 2009) UN Ref QDe.004. Emir for the eastern zone of Af... Individual AKA         The ISIL (Da'esh) and Al-Qaida organisations       01/04/2016      13349
                                                                   00/00/1981 NaN                                           Saudi Arabia     1) Saudi Arabia 2) Qatar Passport No: 592667 (Qatari passport issued on ... NaN       NaN                                                NaN       NaN       NaN       NaN       NaN       NaN       NaN           Afghanistan (since 2009) UN Ref QDe.004. Emir for the eastern zone of Af... Individual AKA         The ISIL (Da'esh) and Al-Qaida organisations       01/04/2016      13349
ANSAR AL SHARIA NaN       NaN           NaN    NaN    NaN    NaN   NaN        NaN                                           NaN              NaN                      NaN                                                NaN       NaN                                                NaN       NaN       NaN       NaN       NaN       NaN       NaN           NaN                      UN REF:QE.A.146.14. Also referred to as Ansar a... Entity     AKA         The ISIL (Da'esh) and Al-Qaida organisations       29/11/2014      13188
IL              Kim Kyong NaN           NaN    NaN    NaN    NaN   01/08/1979 NaN                                           NaN              NaN                      Passport No. 836210029                             NaN       Foreign Trade Bank deputy chief representative ... Libya     NaN       NaN       NaN       NaN       NaN       NaN           NaN                      Annex XIII. UN Listing. UN Ref.KPI.067.            Individual Prime Alias North Korea (Democratic People's Republic of Ko... 22/12/2017      13562
...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ...
ZULKARNAIN      NaN       NaN           NaN    NaN    NaN    NaN   00/00/1963 Gebang village, Masaran, Sragen, Central Java Indonesia        Indonesian               NaN                                                NaN       NaN                                                NaN       NaN       NaN       NaN       NaN       NaN       NaN           NaN                      UN Ref QI.Z.187.05. Also referred to as Murshid.   Individual AKA         The ISIL (Da'esh) and Al-Qaida organisations       18/05/2005       8636
ZULKARNAN       NaN       NaN           NaN    NaN    NaN    NaN   00/00/1963 Gebang village, Masaran, Sragen, Central Java Indonesia        Indonesian               NaN                                                NaN       NaN                                                NaN       NaN       NaN       NaN       NaN       NaN       NaN           NaN                      UN Ref QI.Z.187.05. Also referred to as Murshid.   Individual AKA         The ISIL (Da'esh) and Al-Qaida organisations       18/05/2005       8636
ZULKARNIN       NaN       NaN           NaN    NaN    NaN    NaN   00/00/1963 Gebang village, Masaran, Sragen, Central Java Indonesia        Indonesian               NaN                                                NaN       NaN                                                NaN       NaN       NaN       NaN       NaN       NaN       NaN           NaN                      UN Ref QI.Z.187.05. Also referred to as Murshid.   Individual AKA         The ISIL (Da'esh) and Al-Qaida organisations       18/05/2005       8636
ZYMA            Petro     Anatoliyovych NaN    NaN    NaN    NaN   18/01/1970 Artemivsk, Donetsk Oblast                     Ukraine          NaN                      NaN                                                NaN       Head of the Crimean Security Service (SBU) (Sin... NaN       NaN       NaN       NaN       NaN       NaN       NaN           NaN                      NaN                                                Individual AKA         Ukraine (Sovereignty)                              18/03/2014      12927
                                                                   29/03/1965 Artemivsk, Donetsk Oblast                     Ukraine          NaN                      NaN                                                NaN       Head of the Crimean Security Service (SBU) (Sin... NaN       NaN       NaN       NaN       NaN       NaN       NaN           NaN                      NaN                                                Individual AKA         Ukraine (Sovereignty)                              18/03/2014      12927

[9381 rows x 2 columns]

In [32]:
uk = pd.read_csv('../Datasets/UKHMT Sanctions List.csv', skiprows=[0], engine='python')

In [34]:
uk = pd.read_csv('../Datasets/UKHMT Sanctions List.csv', skiprows=1, engine='python')

In [35]:
uk

,Name 6,Name 1,Name 2,Name 3,Name 4,Name 5,Title,DOB,Town of Birth,Country of Birth,...,Address 6,Post/Zip Code,Country,Other Information,Group Type,Alias Type,Regime,Listed On,Last Updated,Group ID
0,AL-QAHTANI,Sheikh,Farooq,NaN,NaN,NaN,NaN,00/00/1980,NaN,Saudi Arabia,...,NaN,NaN,Afghanistan (since 2009),UN Ref QDe.004. Emir for the eastern zone of A...,Individual,AKA,The ISIL (Da'esh) and Al-Qaida organisations,01/04/2016,01/04/2016,13349
1,AL-QAHTANI,Sheikh,Farooq,NaN,NaN,NaN,NaN,00/00/1981,NaN,Saudi Arabia,...,NaN,NaN,Afghanistan (since 2009),UN Ref QDe.004. Emir for the eastern zone of A...,Individual,AKA,The ISIL (Da'esh) and Al-Qaida organisations,01/04/2016,01/04/2016,13349
2,ANSAR AL SHARIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,UN REF:QE.A.146.14. Also referred to as Ansar ...,Entity,AKA,The ISIL (Da'esh) and Al-Qaida organisations,29/11/2014,02/12/2014,13188
3,IL,Kim Kyong,NaN,NaN,NaN,NaN,NaN,01/08/1979,NaN,NaN,...,NaN,NaN,NaN,Annex XIII. UN Listing. UN Ref.KPI.067.,Individual,Prime Alias,North Korea (Democratic People's Republic of K...,22/12/2017,09/01/2018,13562
4,TONG SAN 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,IMO: 8937675. MMSI: 445539000. The following v...,Entity,Prime Alias,North Korea (Democratic People's Republic of K...,19/10/2017,19/10/2017,13556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9375,ZULKARNAIN,NaN,NaN,NaN,NaN,NaN,NaN,00/00/1963,"Gebang village, Masaran, Sragen, Central Java",Indonesia,...,NaN,NaN,NaN,UN Ref QI.Z.187.05. Also referred to as Murshid.,Individual,AKA,The ISIL (Da'esh) and Al-Qaida organisations,18/05/2005,29/04/2019,8636
9376,ZULKARNAN,NaN,NaN,NaN,NaN,NaN,NaN,00/00/1963,"Gebang village, Masaran, Sragen, Central Java",Indonesia,...,NaN,NaN,NaN,UN Ref QI.Z.187.05. Also referred to as Murshid.,Individual,AKA,The ISIL (Da'esh) and Al-Qaida organisations,18/05/2005,29/04/2019,8636
9377,ZULKARNIN,NaN,NaN,NaN,NaN,NaN,NaN,00/00/1963,"Gebang village, Masaran, Sragen, Central Java",Indonesia,...,NaN,NaN,NaN,UN Ref QI.Z.187.05. Also referred to as Murshid.,Individual,AKA,The ISIL (Da'esh) and Al-Qaida organisations,18/05/2005,29/04/2019,8636
9378,ZYMA,Petro,Anatoliyovych,NaN,NaN,NaN,NaN,18/01/1970,"Artemivsk, Donetsk Oblast",Ukraine,...,NaN,NaN,NaN,NaN,Individual,AKA,Ukraine (Sovereignty),18/03/2014,15/03/2018,12927
9379,ZYMA,Petro,Anatoliyovych,NaN,NaN,NaN,NaN,29/03/1965,"Artemivsk, Donetsk Oblast",Ukraine,...,NaN,NaN,NaN,NaN,Individual,AKA,Ukraine (Sovereignty),18/03/2014,15/03/2018,12927

In [36]:
uk = pd.read_csv('../Datasets/UKHMT Sanctions List.csv', skipfooter=2, header=1, engine='python')

In [38]:
uk

,Name 6,Name 1,Name 2,Name 3,Name 4,Name 5,Title,DOB,Town of Birth,Country of Birth,...,Address 6,Post/Zip Code,Country,Other Information,Group Type,Alias Type,Regime,Listed On,Last Updated,Group ID
0,AL-QAHTANI,Sheikh,Farooq,NaN,NaN,NaN,NaN,00/00/1980,NaN,Saudi Arabia,...,NaN,NaN,Afghanistan (since 2009),UN Ref QDe.004. Emir for the eastern zone of A...,Individual,AKA,The ISIL (Da'esh) and Al-Qaida organisations,01/04/2016,01/04/2016,13349
1,AL-QAHTANI,Sheikh,Farooq,NaN,NaN,NaN,NaN,00/00/1981,NaN,Saudi Arabia,...,NaN,NaN,Afghanistan (since 2009),UN Ref QDe.004. Emir for the eastern zone of A...,Individual,AKA,The ISIL (Da'esh) and Al-Qaida organisations,01/04/2016,01/04/2016,13349
2,ANSAR AL SHARIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,UN REF:QE.A.146.14. Also referred to as Ansar ...,Entity,AKA,The ISIL (Da'esh) and Al-Qaida organisations,29/11/2014,02/12/2014,13188
3,IL,Kim Kyong,NaN,NaN,NaN,NaN,NaN,01/08/1979,NaN,NaN,...,NaN,NaN,NaN,Annex XIII. UN Listing. UN Ref.KPI.067.,Individual,Prime Alias,North Korea (Democratic People's Republic of K...,22/12/2017,09/01/2018,13562
4,TONG SAN 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,IMO: 8937675. MMSI: 445539000. The following v...,Entity,Prime Alias,North Korea (Democratic People's Republic of K...,19/10/2017,19/10/2017,13556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9373,ZULKARNAEN,NaN,NaN,NaN,NaN,NaN,NaN,00/00/1963,"Gebang village, Masaran, Sragen, Central Java",Indonesia,...,NaN,NaN,NaN,UN Ref QI.Z.187.05. Also referred to as Murshid.,Individual,AKA,The ISIL (Da'esh) and Al-Qaida organisations,18/05/2005,29/04/2019,8636
9374,ZULKARNAEN,Ustad,Daud,NaN,NaN,NaN,NaN,00/00/1963,"Gebang village, Masaran, Sragen, Central Java",Indonesia,...,NaN,NaN,NaN,UN Ref QI.Z.187.05. Also referred to as Murshid.,Individual,AKA,The ISIL (Da'esh) and Al-Qaida organisations,18/05/2005,29/04/2019,8636
9375,ZULKARNAIN,NaN,NaN,NaN,NaN,NaN,NaN,00/00/1963,"Gebang village, Masaran, Sragen, Central Java",Indonesia,...,NaN,NaN,NaN,UN Ref QI.Z.187.05. Also referred to as Murshid.,Individual,AKA,The ISIL (Da'esh) and Al-Qaida organisations,18/05/2005,29/04/2019,8636
9376,ZULKARNAN,NaN,NaN,NaN,NaN,NaN,NaN,00/00/1963,"Gebang village, Masaran, Sragen, Central Java",Indonesia,...,NaN,NaN,NaN,UN Ref QI.Z.187.05. Also referred to as Murshid.,Individual,AKA,The ISIL (Da'esh) and Al-Qaida organisations,18/05/2005,29/04/2019,8636
9377,ZULKARNIN,NaN,NaN,NaN,NaN,NaN,NaN,00/00/1963,"Gebang village, Masaran, Sragen, Central Java",Indonesia,...,NaN,NaN,NaN,UN Ref QI.Z.187.05. Also referred to as Murshid.,Individual,AKA,The ISIL (Da'esh) and Al-Qaida organisations,18/05/2005,29/04/2019,8636

In [39]:
uk = pd.read_csv('../Datasets/UKHMT Sanctions List.csv', nrows=100, header=1, engine='python')

In [46]:
uk.shape

(100, 29)

In [52]:
ofac = pd.read_csv('http://bit.ly/ofac_sanctions_csv', na_values='', header=None, names=['ent_num','SDN_Name','SDN_Type','Program','Title','Call_Sign','Vess_type','Tonnage','GRT','Vess_flag','Vess_owner','Remarks'])

In [53]:
ofac.tail()

,ent_num,SDN_Name,SDN_Type,Program,Title,Call_Sign,Vess_type,Tonnage,GRT,Vess_flag,Vess_owner,Remarks
371,23571.0,STRAKHOVOVE OBSHCHESTVO SURGUTNEFTEGAZ OOO,-0-,UKRAINE-EO13662,-0-,-0-,-0-,-0-,-0-,-0-,-0-,Website www.sngi.ru; Executive Order 13662 Dir...
372,23572.0,KIRISHIAVTOSERVIS OOO,-0-,UKRAINE-EO13662,-0-,-0-,-0-,-0-,-0-,-0-,-0-,Website www.kirishiavtoservis.ru; Executive Or...
373,23577.0,SNGB AO,-0-,UKRAINE-EO13662,-0-,-0-,-0-,-0-,-0-,-0-,-0-,Website www.sngb.ru; Executive Order 13662 Dir...
374,26182.0,"KAYAKIRAN, Evren",individual,FSE-IR,-0-,-0-,-0-,-0-,-0-,-0-,-0-,DOB 08 Feb 1980; citizen Turkey; Gender Male; ...
375,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
ofac.dropna(how='all', axis=0)

,ent_num,SDN_Name,SDN_Type,Program,Title,Call_Sign,Vess_type,Tonnage,GRT,Vess_flag,Vess_owner,Remarks
0,9639.0,"HANIYA, Ismail Abdul Salah",individual,NS-PLC,-0-,-0-,-0-,-0-,-0-,-0-,-0-,DOB 1962; POB Shati.
1,9640.0,"ABU TEIR, Mohammed",individual,NS-PLC,-0-,-0-,-0-,-0-,-0-,-0-,-0-,DOB 1951; POB Umm Tuba.
2,9641.0,"AL-SHANTI, Jamileh Abdullah",individual,NS-PLC,-0-,-0-,-0-,-0-,-0-,-0-,-0-,DOB 1955; POB Jabalia Camp.
3,9642.0,"NU'MAN ALAEDDIN, Mohammed Jamal",individual,NS-PLC,-0-,-0-,-0-,-0-,-0-,-0-,-0-,DOB 1959.
4,9643.0,"MANSOUR, Yasser Daoud",individual,NS-PLC,-0-,-0-,-0-,-0-,-0-,-0-,-0-,"DOB 1967; POB Nablus, West Bank."
...,...,...,...,...,...,...,...,...,...,...,...,...
370,23570.0,SO TVERNEFTEPRODUKT OOO,-0-,UKRAINE-EO13662,-0-,-0-,-0-,-0-,-0-,-0-,-0-,Website www.tvernefteproduct.ru; Email Address...
371,23571.0,STRAKHOVOVE OBSHCHESTVO SURGUTNEFTEGAZ OOO,-0-,UKRAINE-EO13662,-0-,-0-,-0-,-0-,-0-,-0-,-0-,Website www.sngi.ru; Executive Order 13662 Dir...
372,23572.0,KIRISHIAVTOSERVIS OOO,-0-,UKRAINE-EO13662,-0-,-0-,-0-,-0-,-0-,-0-,-0-,Website www.kirishiavtoservis.ru; Executive Or...
373,23577.0,SNGB AO,-0-,UKRAINE-EO13662,-0-,-0-,-0-,-0-,-0-,-0-,-0-,Website www.sngb.ru; Executive Order 13662 Dir...
374,26182.0,"KAYAKIRAN, Evren",individual,FSE-IR,-0-,-0-,-0-,-0-,-0-,-0-,-0-,DOB 08 Feb 1980; citizen Turkey; Gender Male; ...

In [55]:
uk = pd.read_csv('../Datasets/UKHMT Sanctions List.csv', skiprows=1, parse_dates=['Listed On', 'Last Updated'], engine='python')

In [56]:
uk.dtypes

Name 6                       object
Name 1                       object
Name 2                       object
Name 3                       object
Name 4                       object
Name 5                       object
Title                        object
DOB                          object
Town of Birth                object
Country of Birth             object
Nationality                  object
Passport Details             object
NI Number                    object
Position                     object
Address 1                    object
Address 2                    object
Address 3                    object
Address 4                    object
Address 5                    object
Address 6                    object
Post/Zip Code                object
Country                      object
Other Information            object
Group Type                   object
Alias Type                   object
Regime                       object
Listed On            datetime64[ns]
Last Updated         datetime64[ns]
Group ID                      int64
dtype: object

In [57]:
df = pd.DataFrame({'dates': ['2020-01-24', '2020-01-23'], 'time': ['22:00', '21:00']})

In [58]:
df

        dates   time
0  2020-01-24  22:00
1  2020-01-23  21:00

In [59]:
df.to_csv('my_df.csv', index=False)

In [65]:
df_csv = pd.read_csv('my_df.csv', parse_dates={'dt': ['dates', 'time']},keep_date_col=True)

In [63]:
df_csv

                   dt
0 2020-01-24 22:00:00
1 2020-01-23 21:00:00

In [66]:
df_csv.dtypes

dt       datetime64[ns]
dates            object
time             object
dtype: object

In [67]:
pd.to_datetime(df_csv.dates)

0   2020-01-24
1   2020-01-23
Name: dates, dtype: datetime64[ns]

In [68]:
list = []
for chunk in pd.read_csv('../Datasets/UKHMT Sanctions List.csv', chunksize=200, skiprows=1, engine='python'):
    list.append(chunk)
uk_csv = pd.concat(list)

In [69]:
chunk

,Name 6,Name 1,Name 2,Name 3,Name 4,Name 5,Title,DOB,Town of Birth,Country of Birth,...,Address 6,Post/Zip Code,Country,Other Information,Group Type,Alias Type,Regime,Listed On,Last Updated,Group ID
9200,YUN,Chang,Hyok,NaN,NaN,NaN,NaN,09/08/1965,NaN,NaN,...,NaN,NaN,NaN,Annex XV EU not UN Listing. Responsible for su...,Individual,Prime Alias,North Korea (Democratic People's Republic of K...,20/05/2016,15/09/2017,13374
9201,YUN,Jong,Rin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Annex XV EU not UN Listing. Former Member of ...,Individual,AKA,North Korea (Democratic People's Republic of K...,20/05/2016,15/09/2017,13370
9202,YUN,Jong-rin,NaN,NaN,NaN,NaN,General,NaN,NaN,NaN,...,NaN,NaN,NaN,Annex XV EU not UN Listing. Former Member of ...,Individual,Prime Alias,North Korea (Democratic People's Republic of K...,20/05/2016,15/09/2017,13370
9203,YUNES,Jamal,NaN,NaN,NaN,NaN,Brigadier General,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Individual,Prime Alias,Syria,24/01/2012,31/05/2013,12472
9204,YUNES,Tawfig,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Former Head of the Department for Internal Sec...,Individual,AKA,Syria,02/08/2011,22/05/2019,12025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9375,ZULKARNAIN,NaN,NaN,NaN,NaN,NaN,NaN,00/00/1963,"Gebang village, Masaran, Sragen, Central Java",Indonesia,...,NaN,NaN,NaN,UN Ref QI.Z.187.05. Also referred to as Murshid.,Individual,AKA,The ISIL (Da'esh) and Al-Qaida organisations,18/05/2005,29/04/2019,8636
9376,ZULKARNAN,NaN,NaN,NaN,NaN,NaN,NaN,00/00/1963,"Gebang village, Masaran, Sragen, Central Java",Indonesia,...,NaN,NaN,NaN,UN Ref QI.Z.187.05. Also referred to as Murshid.,Individual,AKA,The ISIL (Da'esh) and Al-Qaida organisations,18/05/2005,29/04/2019,8636
9377,ZULKARNIN,NaN,NaN,NaN,NaN,NaN,NaN,00/00/1963,"Gebang village, Masaran, Sragen, Central Java",Indonesia,...,NaN,NaN,NaN,UN Ref QI.Z.187.05. Also referred to as Murshid.,Individual,AKA,The ISIL (Da'esh) and Al-Qaida organisations,18/05/2005,29/04/2019,8636
9378,ZYMA,Petro,Anatoliyovych,NaN,NaN,NaN,NaN,18/01/1970,"Artemivsk, Donetsk Oblast",Ukraine,...,NaN,NaN,NaN,NaN,Individual,AKA,Ukraine (Sovereignty),18/03/2014,15/03/2018,12927
9379,ZYMA,Petro,Anatoliyovych,NaN,NaN,NaN,NaN,29/03/1965,"Artemivsk, Donetsk Oblast",Ukraine,...,NaN,NaN,NaN,NaN,Individual,AKA,Ukraine (Sovereignty),18/03/2014,15/03/2018,12927

In [70]:
uk_csv

,Name 6,Name 1,Name 2,Name 3,Name 4,Name 5,Title,DOB,Town of Birth,Country of Birth,...,Address 6,Post/Zip Code,Country,Other Information,Group Type,Alias Type,Regime,Listed On,Last Updated,Group ID
0,AL-QAHTANI,Sheikh,Farooq,NaN,NaN,NaN,NaN,00/00/1980,NaN,Saudi Arabia,...,NaN,NaN,Afghanistan (since 2009),UN Ref QDe.004. Emir for the eastern zone of A...,Individual,AKA,The ISIL (Da'esh) and Al-Qaida organisations,01/04/2016,01/04/2016,13349
1,AL-QAHTANI,Sheikh,Farooq,NaN,NaN,NaN,NaN,00/00/1981,NaN,Saudi Arabia,...,NaN,NaN,Afghanistan (since 2009),UN Ref QDe.004. Emir for the eastern zone of A...,Individual,AKA,The ISIL (Da'esh) and Al-Qaida organisations,01/04/2016,01/04/2016,13349
2,ANSAR AL SHARIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,UN REF:QE.A.146.14. Also referred to as Ansar ...,Entity,AKA,The ISIL (Da'esh) and Al-Qaida organisations,29/11/2014,02/12/2014,13188
3,IL,Kim Kyong,NaN,NaN,NaN,NaN,NaN,01/08/1979,NaN,NaN,...,NaN,NaN,NaN,Annex XIII. UN Listing. UN Ref.KPI.067.,Individual,Prime Alias,North Korea (Democratic People's Republic of K...,22/12/2017,09/01/2018,13562
4,TONG SAN 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,IMO: 8937675. MMSI: 445539000. The following v...,Entity,Prime Alias,North Korea (Democratic People's Republic of K...,19/10/2017,19/10/2017,13556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9375,ZULKARNAIN,NaN,NaN,NaN,NaN,NaN,NaN,00/00/1963,"Gebang village, Masaran, Sragen, Central Java",Indonesia,...,NaN,NaN,NaN,UN Ref QI.Z.187.05. Also referred to as Murshid.,Individual,AKA,The ISIL (Da'esh) and Al-Qaida organisations,18/05/2005,29/04/2019,8636
9376,ZULKARNAN,NaN,NaN,NaN,NaN,NaN,NaN,00/00/1963,"Gebang village, Masaran, Sragen, Central Java",Indonesia,...,NaN,NaN,NaN,UN Ref QI.Z.187.05. Also referred to as Murshid.,Individual,AKA,The ISIL (Da'esh) and Al-Qaida organisations,18/05/2005,29/04/2019,8636
9377,ZULKARNIN,NaN,NaN,NaN,NaN,NaN,NaN,00/00/1963,"Gebang village, Masaran, Sragen, Central Java",Indonesia,...,NaN,NaN,NaN,UN Ref QI.Z.187.05. Also referred to as Murshid.,Individual,AKA,The ISIL (Da'esh) and Al-Qaida organisations,18/05/2005,29/04/2019,8636
9378,ZYMA,Petro,Anatoliyovych,NaN,NaN,NaN,NaN,18/01/1970,"Artemivsk, Donetsk Oblast",Ukraine,...,NaN,NaN,NaN,NaN,Individual,AKA,Ukraine (Sovereignty),18/03/2014,15/03/2018,12927
9379,ZYMA,Petro,Anatoliyovych,NaN,NaN,NaN,NaN,29/03/1965,"Artemivsk, Donetsk Oblast",Ukraine,...,NaN,NaN,NaN,NaN,Individual,AKA,Ukraine (Sovereignty),18/03/2014,15/03/2018,12927

In [73]:
zip_csv = pd.read_csv('../Datasets/UKHMT Sanctions List.zip', compression='zip', skiprows=1, engine='python')

In [74]:
zip_csv

,Name 6,Name 1,Name 2,Name 3,Name 4,Name 5,Title,DOB,Town of Birth,Country of Birth,...,Address 6,Post/Zip Code,Country,Other Information,Group Type,Alias Type,Regime,Listed On,Last Updated,Group ID
0,AL-QAHTANI,Sheikh,Farooq,NaN,NaN,NaN,NaN,00/00/1980,NaN,Saudi Arabia,...,NaN,NaN,Afghanistan (since 2009),UN Ref QDe.004. Emir for the eastern zone of A...,Individual,AKA,The ISIL (Da'esh) and Al-Qaida organisations,01/04/2016,01/04/2016,13349
1,AL-QAHTANI,Sheikh,Farooq,NaN,NaN,NaN,NaN,00/00/1981,NaN,Saudi Arabia,...,NaN,NaN,Afghanistan (since 2009),UN Ref QDe.004. Emir for the eastern zone of A...,Individual,AKA,The ISIL (Da'esh) and Al-Qaida organisations,01/04/2016,01/04/2016,13349
2,ANSAR AL SHARIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,UN REF:QE.A.146.14. Also referred to as Ansar ...,Entity,AKA,The ISIL (Da'esh) and Al-Qaida organisations,29/11/2014,02/12/2014,13188
3,IL,Kim Kyong,NaN,NaN,NaN,NaN,NaN,01/08/1979,NaN,NaN,...,NaN,NaN,NaN,Annex XIII. UN Listing. UN Ref.KPI.067.,Individual,Prime Alias,North Korea (Democratic People's Republic of K...,22/12/2017,09/01/2018,13562
4,TONG SAN 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,IMO: 8937675. MMSI: 445539000. The following v...,Entity,Prime Alias,North Korea (Democratic People's Republic of K...,19/10/2017,19/10/2017,13556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9375,ZULKARNAIN,NaN,NaN,NaN,NaN,NaN,NaN,00/00/1963,"Gebang village, Masaran, Sragen, Central Java",Indonesia,...,NaN,NaN,NaN,UN Ref QI.Z.187.05. Also referred to as Murshid.,Individual,AKA,The ISIL (Da'esh) and Al-Qaida organisations,18/05/2005,29/04/2019,8636
9376,ZULKARNAN,NaN,NaN,NaN,NaN,NaN,NaN,00/00/1963,"Gebang village, Masaran, Sragen, Central Java",Indonesia,...,NaN,NaN,NaN,UN Ref QI.Z.187.05. Also referred to as Murshid.,Individual,AKA,The ISIL (Da'esh) and Al-Qaida organisations,18/05/2005,29/04/2019,8636
9377,ZULKARNIN,NaN,NaN,NaN,NaN,NaN,NaN,00/00/1963,"Gebang village, Masaran, Sragen, Central Java",Indonesia,...,NaN,NaN,NaN,UN Ref QI.Z.187.05. Also referred to as Murshid.,Individual,AKA,The ISIL (Da'esh) and Al-Qaida organisations,18/05/2005,29/04/2019,8636
9378,ZYMA,Petro,Anatoliyovych,NaN,NaN,NaN,NaN,18/01/1970,"Artemivsk, Donetsk Oblast",Ukraine,...,NaN,NaN,NaN,NaN,Individual,AKA,Ukraine (Sovereignty),18/03/2014,15/03/2018,12927
9379,ZYMA,Petro,Anatoliyovych,NaN,NaN,NaN,NaN,29/03/1965,"Artemivsk, Donetsk Oblast",Ukraine,...,NaN,NaN,NaN,NaN,Individual,AKA,Ukraine (Sovereignty),18/03/2014,15/03/2018,12927